name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    permissions: write-all

    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Download Website Dependencies
        working-directory: ./frontend/src
        run: npm ci

      - name: Create Env file 
        working-directory: ./frontend/src
        run: echo "VITE_DOMAIN_NAME=insertdomainnamehere.local" > .env

      - name: Build Website
        working-directory: ./frontend/src
        run: npm run build

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Download Go Modules for Validation Test
        working-directory: tests/validate
        run: go mod download
      - name: Run Validation Test
        working-directory: tests/validate
        run: go test -v -tags=validate

      - name: Download Go Modules for Unit Tests
        working-directory: tests/unit
        run: go mod download

      - name: Run Unit Tests
        working-directory: tests/unit
        run: go test -v -tags=unit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download Go Modules for Integration Tests
        working-directory: tests/integration
        run: go mod download
      - name: Run Integration Tests
        working-directory: tests/integration
        run: go test -v -tags=integration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_DOMAIN: ${{ vars.CLOUDFLARE_DOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
      


